# Generated by Django 4.1.3 on 2022-12-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_auto_20221226_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
