# Generated by Django 4.1.3 on 2022-12-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_alter_activity_date_time_alter_photo_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
