# Generated by Django 4.1.3 on 2022-12-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_photo_caption_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
