# Generated by Django 4.1.3 on 2022-12-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_photo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ManyToManyField(to='webserver.photo')),
            ],
        ),
    ]
