# Generated by Django 4.1.3 on 2023-01-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_name',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
